- name: Task level variables
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: printexample.com

- name: Vars from inventory
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: facts
  hosts: localhost
  tasks:
    - name: Print Hostname
      ansible.builtin.debug:
        msg: host name = {{ansible_hostname}}





