- name: Register variables
  hosts: localhost
  tasks:
    - name: run uptime command
      ansible.builtin.shell: uptime
      register: output
    - name: Print output of the shell
      ansible.builtin.debug:
        msg:  Print "{{output.stdout}}"



- name: Register variables
  hosts: localhost
  tasks:
    - name: run uptime command
      ansible.builtin.shell: uptime
      register: output
    - name: store in a standard variable
      ansible.builtin.set_fact: uptime
      UPTIME: "{{output.stdout}}"
    - name: Print output of the shell
      ansible.builtin.debug:
      msg:  Print "{{UPTIME}}"
