- name: Register variables
  hosts: localhost
  tasks:
    - name: run uptime command
      ansible.builtin.shell: uptime
      register: output
    - name: Print output of the shell
      ansible.builtin.debug:
        msg:  Print "{{ output }}"
